### ISSUE TITLE
Consider taller status line

### ISSUE THREAD

**Issue by jpcompton** [daelsepara/green-blood#1]
Despite its size, Green Blood is still plausibly playable on certain 8-bit targets (like Ozmoo Commodore 64 in multi-drive or 1581 mode, possibly others) but the status line as coded can't be displayed properly on older, narrow screens. Please consider making the status line taller and reformatting.

<img width="910" alt="Screen Shot 2020-07-06 at 9 26 42 AM" src="https://user-images.githubusercontent.com/51372049/86609083-08ea3d80-bf71-11ea-9f37-49d95d70c7e9.png">

**Comment by daelsepara** [comment]
- status line is now 2 rows
- re-arranged (row 1: paragraph number, Life, row 2: character, gold)
- removed moves count

**Comment by daelsepara** [comment]
closing this issue
