### ISSUE TITLE
Interface recommendations

### ISSUE THREAD

**Issue by jpcompton** [daelsepara/green-blood#2]
Two concrete suggestions:

1. Grazing the Q key seems to irreparably end the game. Command line frotz, at least, cannot UNDO from it even though UNDO is offered. At the very least an "Are you sure Y/N?" check seems advisable.

2. It would be player-friendly to display the non-obvious commands (q, c, g) when the player presses either the h or ? keys, as those are common keys to try for help.

**Comment by daelsepara** [comment]
Great suggestions. Will implement this. Thanks.

**Comment by daelsepara** [comment]
- Addtional command keys displayed when H or ? is pressed during action selection
- User is asked to confirm Quit command
- Removed RESTORE, UNDO on game over message as they aren't implemented

**Comment by daelsepara** [comment]
closing
