### ISSUE TITLE
Excess "press key to continue" between intro and "Choose a character"

### ISSUE THREAD

**Issue by jpcompton** [daelsepara/green-blood#3]
There's a silent [MORE] happening *after* the "Press a key to continue" prompt that follows the intro (ending with "...you can choose which skill to use in that situation") but precedes "Choose a character." (can replicate on frotz and ozmoo). So one has to hit two keys to continue to the choose screen, not just one.

**Comment by daelsepara** [comment]
Removed the extra pause between instructions and character selection. Thanks for the great suggestions!
