### ISSUE TITLE
Statusline is set to two lines but only top line is filled

### ISSUE THREAD

**Issue by fredrikr** [daelsepara/green-blood#6]
Just when you have selected your character, the top window is set to two lines. However, only the top line is filled with reverse spaces, so some random piece of text just sticks around on line 2. When the game starts properly, the second line is filled with reverse characters as well.

![image](https://user-images.githubusercontent.com/1001548/206900971-39c8a48e-3aff-4c2c-bd2d-ab2bbf154ebf.png)

(In this case "ARCHERY" happened to be on line 2 when the statusline was created)

**Comment by daelsepara** [comment]
Thanks for reporting. I made a fix in the latest story file
